import {
  NotificationDetailsProps,
  PostsInfoType,
  SearchDetailProps,
  TopPostsProps,
} from "./types";

export const TopPosts: TopPostsProps = [
  {
    postTitle:
      "My Developer Setup: The 12 Tools That Transformed My Daily Workflow",
    postLink:
      "teamcamp/my-developer-setup-the-12-tools-that-transformed-my-daily-workflow-2i3m",
    numberOfComments: 3,
  },
  {
    postTitle: "How to Optimize React Performance in Large Applications",
    postLink: "react-optimization-guide",
    numberOfComments: 12,
  },
  {
    postTitle: "Building Scalable APIs with Node.js and Express",
    postLink: "nodejs-api-tutorial",
    numberOfComments: 8,
  },
  {
    postTitle: "The Future of Web Development: Trends to Watch in 2025",
    postLink: "web-dev-trends-2025",
    numberOfComments: 15,
  },
  {
    postTitle: "Mastering TypeScript: Advanced Patterns and Best Practices",
    postLink: "typescript-advanced-patterns",
    numberOfComments: 7,
  },
  {
    postTitle: "CSS Grid vs Flexbox: When to Use Which Layout System",
    postLink: "css-grid-vs-flexbox",
    numberOfComments: 10,
  },
  {
    postTitle: "Securing Your Web Applications: Essential Security Practices",
    postLink: "web-security-best-practices",
    numberOfComments: 6,
  },
];

export const PostInfo: PostsInfoType = [
  {
    postId: "32155w7f2152t8esjh85yt",
    authorName: "Prathamesh patil",
    authorPic: "/logo/me.webp",
    postCreationDate: "2025-09-08",
    tags: ["facts", "student_life", "im_important"],
    postType: "Article",
    postTitle: "No good quality food in hostel",
    postDesc:
      "This article discusses the ongoing issues with food quality in the hostel mess, highlighting student complaints and suggestions for improvement.",
    postImage: "/post1.webp",
    postLikes: 25000,
    postComments: [
      "Prathamesh, tum age badho ham tumhare saath hai!",
      "Fuck mess-Food!!!!!",
      "Ye bhadwa college",
    ],
  },
  {
    postId: "45678g9h3210k1lmn23op",
    authorName: "Anjali Sharma",
    authorPic: "/post2.webp",
    postCreationDate: "2025-09-07",
    tags: ["campus_events", "student_life", "fun"],
    postType: "Post",
    postTitle: "Exciting Fest Coming Up!",
    postDesc:
      "Get ready for an amazing campus fest with music, dance, and fun activities. Don't miss out on the performances and events!",
    postImage: "/post2.webp",
    postLikes: 15000,
    postComments: [
      "Can't wait for the performances!",
      "Who's performing?",
      "This is going to be epic!",
    ],
  },
  {
    postId: "78901q2w3456e7r8t9y0u",
    authorName: "Ravi Kumar",
    authorPic: "/post3.webp",
    postCreationDate: "2025-09-06",
    tags: ["study_tips", "exams", "student_life"],
    postType: "Article",
    postTitle: "How to Ace Your Exams",
    postDesc:
      "A comprehensive guide to effective study techniques, time management, and tips to perform well in exams.",
    postImage: "/post3.webp",
    postLikes: 32000,
    postComments: [
      "Great tips, thanks!",
      "I needed this.",
      "More articles like this please.",
    ],
  },
  {
    postId: "12345a6s7d8f9g0h1j2k3",
    authorName: "Sneha Patel",
    authorPic: "/post4.webp",
    postCreationDate: "2025-09-05",
    tags: ["hostel_life", "complaints", "we_need_better_food"],
    postType: "Post",
    postTitle: "Hostel WiFi is Terrible",
    postDesc:
      "Frustrated with slow and unreliable WiFi in the hostel? Share your experiences and let's push for better connectivity.",
    postImage: "/post4.webp",
    postLikes: 18000,
    postComments: [
      "Totally agree!",
      "When will they fix it?",
      "Can't study properly.",
    ],
  },
  {
    postId: "98765z1x2c3v4b5n6m7l8",
    authorName: "Karan Singh",
    authorPic: "/post5.webp",
    postCreationDate: "2025-09-04",
    tags: ["sports", "student_life", "fitness"],
    postType: "Article",
    postTitle: "Benefits of Campus Sports",
    postDesc:
      "Explore how participating in sports on campus improves physical health, mental well-being, and social skills.",
    postImage: "/post5.webp",
    postLikes: 22000,
    postComments: [
      "Love playing football!",
      "Keeps me fit.",
      "More facilities needed.",
    ],
  },
  {
    postId: "abcd1234efgh5678ijkl",
    authorName: "Maya Gupta",
    authorPic: "/post6.webp",
    postCreationDate: "2025-09-03",
    tags: ["library", "study_hacks", "student_life"],
    postType: "Post",
    postTitle: "Best Study Spots on Campus",
    postDesc:
      "Discover the quietest and most productive places to study around campus, from the library to hidden corners.",
    postImage: "/post6.webp",
    postLikes: 12000,
    postComments: ["The library is my go-to!", "Thanks for the tips."],
  },
  {
    postId: "mnop9012qrst3456uvwx",
    authorName: "Vikram Rao",
    authorPic: "/post7.jpg",
    postCreationDate: "2025-09-02",
    tags: ["mental_health", "wellness", "student_life"],
    postType: "Article",
    postTitle: "Managing Stress During Exams",
    postDesc:
      "Tips and strategies for staying calm and focused during exam season, including mindfulness and self-care.",
    postImage: "/post7.jpg",
    postLikes: 28000,
    postComments: ["This is so helpful!", "I need to try these."],
  },
];

export const notificationDetails: NotificationDetailsProps = [
  {
    user: "Prathamesh Patil",
    userPic: "/post1.webp",
    time: "4 hours ago",
    postTitle: "Advanced Use of Weak References in Memory Management",
    tags: ["javascript", "programming", "webdev", "advanced"],
    notificationType: "post",
    authorProfile: "/prathamesh-patil-5090",
    postLink: "/post/21",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Alice Johnson",
    userPic: "/post3.webp",
    time: "2 hours ago",
    postTitle: "Top 10 Gaming Tips for Beginners",
    tags: ["gaming", "tips", "beginners"],
    notificationType: "comment",
    authorProfile: "/prathamesh-patil-5090",
    postLink: "/post/21",
    comment:
      "Great tips! I've been looking for ways to improve my gaming skills. The tip about practice routines is especially helpful.",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Bob Smith",
    userPic: "/post2.webp",
    time: "1 day ago",
    postTitle: "Exploring Modern Art Techniques",
    tags: ["art", "creativity", "techniques"],
    notificationType: "post",
    authorProfile: "/bob-smith",
    postLink: "/post/22",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Diana Prince",
    userPic: "/post4.webp",
    time: "about 1 week ago",
    postTitle: "Healthy Recipes for Busy Professionals",
    tags: ["cooking", "health", "recipes"],
    notificationType: "post",
    authorProfile: "/diana-prince",
    postLink: "/post/24",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Eve Wilson",
    userPic: "/post5.webp",
    time: "2 weeks ago",
    postTitle: "Fitness Routines for All Ages",
    tags: ["fitness", "health", "routines"],
    notificationType: "comment",
    authorProfile: "/eve-wilson",
    postLink: "/post/25",
    comment:
      "Love these fitness routines! The modifications for different age groups are really thoughtful and inclusive.",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Frank Miller",
    userPic: "/post6.webp",
    time: "1 month ago",
    postTitle: "Travel Stories from Around the World",
    tags: ["travel", "stories", "adventure"],
    notificationType: "post",
    authorProfile: "/frank-miller",
    postLink: "/post/26",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Sarah Connor",
    userPic: "/post1.webp",
    time: "30 minutes ago",
    postTitle: "Advanced Use of Weak References in Memory Management",
    tags: ["javascript", "programming", "webdev", "advanced"],
    notificationType: "comment",
    authorProfile: "/sarah-connor",
    postLink: "/post/21",
    comment:
      "Excellent explanation of weak references! This really helped me understand memory management better in JavaScript.",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    user: "Mike Johnson",
    userPic: "/post3.webp",
    time: "45 minutes ago",
    postTitle: "Latest News in Tech: AI Breakthroughs",
    tags: ["news", "tech", "ai"],
    notificationType: "comment",
    authorProfile: "/mike-johnson",
    postLink: "/post/23",
    comment:
      "The AI developments mentioned here are groundbreaking! Can't wait to see how these technologies evolve.",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
];

export const SearchDetails: SearchDetailProps = [
  {
    type: "posts",
    user: "Alice Johnson",
    userPic: "/post3.webp",
    time: "2 hours ago",
    postTitle: "Top 10 Gaming Tips for Beginners",
    tags: ["gaming", "tips", "beginners"],
    authorProfile: "/prathamesh-patil-5090",
    postLink: "/post/21",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    type: "people",
    user: "Bob Smith",
    userPic: "/post2.webp",
    profileLink: "/bob-smith",
    bio: "Artist and creative enthusiast sharing modern techniques.",
    followers: 1500,
  },
  {
    type: "organizations",
    name: "Tech Innovators Inc.",
    logo: "/org1.webp",
    description: "Leading organization in tech innovation and development.",
    website: "https://techinnovators.com",
    members: 5000,
  },
  {
    type: "tags",
    tag: "javascript",
    count: 1200,
    description: "Posts related to JavaScript programming and web development.",
  },
  {
    type: "comments",
    user: "Eve Wilson",
    userPic: "/post5.webp",
    time: "2 weeks ago",
    postTitle: "Fitness Routines for All Ages",
    tags: ["fitness", "health", "routines"],
    authorProfile: "/eve-wilson",
    postLink: "/post/25",
    comment:
      "Love these fitness routines! The modifications for different age groups are really thoughtful and inclusive.",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    type: "my posts only",
    postId: "32155w7f2152t8esjh85yt",
    authorName: "Prathamesh Patil",
    authorPic: "/logo/me.webp",
    postCreationDate: "2025-09-08",
    tags: ["facts", "student_life", "im_important"],
    postType: "Article",
    postTitle: "No good quality food in hostel",
    postDesc:
      "This article discusses the ongoing issues with food quality in the hostel mess, highlighting student complaints and suggestions for improvement.",
    postImage: "/post1.webp",
    postLikes: 25000,
    postComments: [
      "Prathamesh, tum age badho ham tumhare saath hai!",
      "Fuck mess-Food!!!!!",
      "Ye bhadwa college",
    ],
  },
  {
    type: "posts",
    user: "Diana Prince",
    userPic: "/post4.webp",
    time: "about 1 week ago",
    postTitle: "Healthy Recipes for Busy Professionals",
    tags: ["cooking", "health", "recipes"],
    authorProfile: "/diana-prince",
    postLink: "/post/24",
    isLiked: false,
    isSaved: false,
    isSubscribed: false,
  },
  {
    type: "people",
    user: "Sarah Connor",
    userPic: "/post1.webp",
    profileLink: "/sarah-connor",
    bio: "Tech enthusiast and programmer specializing in AI and memory management.",
    followers: 2200,
  },
  {
    type: "organizations",
    name: "Art Collective",
    logo: "/org2.webp",
    description:
      "A community for artists to share and collaborate on creative projects.",
    website: "https://artcollective.org",
    members: 800,
  },
  {
    type: "tags",
    tag: "fitness",
    count: 950,
    description: "Content about health, exercise, and wellness routines.",
  },
];
